package com.awelee.mapper;

import com.awelee.model.FbsBusinessReport;
import com.awelee.model.FbsBusinessReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FbsBusinessReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int countByExample(FbsBusinessReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int deleteByExample(FbsBusinessReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int insert(FbsBusinessReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int insertSelective(FbsBusinessReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    List<FbsBusinessReport> selectByExample(FbsBusinessReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    FbsBusinessReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") FbsBusinessReport record, @Param("example") FbsBusinessReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int updateByExample(@Param("record") FbsBusinessReport record, @Param("example") FbsBusinessReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int updateByPrimaryKeySelective(FbsBusinessReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_business_report
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    int updateByPrimaryKey(FbsBusinessReport record);
}