package com.awelee.mapper;

import com.awelee.model.FbsReceiptReport;
import com.awelee.model.FbsReceiptReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FbsReceiptReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int countByExample(FbsReceiptReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int deleteByExample(FbsReceiptReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int insert(FbsReceiptReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int insertSelective(FbsReceiptReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    List<FbsReceiptReport> selectByExample(FbsReceiptReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    FbsReceiptReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") FbsReceiptReport record, @Param("example") FbsReceiptReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int updateByExample(@Param("record") FbsReceiptReport record, @Param("example") FbsReceiptReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int updateByPrimaryKeySelective(FbsReceiptReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    int updateByPrimaryKey(FbsReceiptReport record);
}