package com.awelee.model;

import com.awelee.tools.excel.ExcelAttribute;

public class FbsBusinessReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.id
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.contract_no
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="合同编号",column = "A")
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.business_type
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="业务类型",column = "B")
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.customer_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="客户姓名",column = "C")
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.owner_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="业主姓名",column = "D")
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.business_end_date
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="业务完结日期",column = "E")
    private String businessEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.total_income_receivable
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="应收总收入",column = "F")
    private String totalIncomeReceivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.approval_status
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="审批状态",column = "G")
    private String approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.department
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="部门",column = "H")
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.department_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="部门编码",column = "I")
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.region
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="大区",column = "J")
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.region_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="大区编码",column = "K")
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.group_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="组团名",column = "L")
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.group_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="组团编码",column = "M")
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.deal_shop
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="成交店",column = "N")
    private String dealShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_business_report.store_number
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    @ExcelAttribute(name="店面编码",column = "O")
    private String storeNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.id
     *
     * @return the value of fbs_business_report.id
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.id
     *
     * @param id the value for fbs_business_report.id
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.contract_no
     *
     * @return the value of fbs_business_report.contract_no
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.contract_no
     *
     * @param contractNo the value for fbs_business_report.contract_no
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.business_type
     *
     * @return the value of fbs_business_report.business_type
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.business_type
     *
     * @param businessType the value for fbs_business_report.business_type
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.customer_name
     *
     * @return the value of fbs_business_report.customer_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.customer_name
     *
     * @param customerName the value for fbs_business_report.customer_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.owner_name
     *
     * @return the value of fbs_business_report.owner_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.owner_name
     *
     * @param ownerName the value for fbs_business_report.owner_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.business_end_date
     *
     * @return the value of fbs_business_report.business_end_date
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getBusinessEndDate() {
        return businessEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.business_end_date
     *
     * @param businessEndDate the value for fbs_business_report.business_end_date
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setBusinessEndDate(String businessEndDate) {
        this.businessEndDate = businessEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.total_income_receivable
     *
     * @return the value of fbs_business_report.total_income_receivable
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getTotalIncomeReceivable() {
        return totalIncomeReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.total_income_receivable
     *
     * @param totalIncomeReceivable the value for fbs_business_report.total_income_receivable
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setTotalIncomeReceivable(String totalIncomeReceivable) {
        this.totalIncomeReceivable = totalIncomeReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.approval_status
     *
     * @return the value of fbs_business_report.approval_status
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.approval_status
     *
     * @param approvalStatus the value for fbs_business_report.approval_status
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.department
     *
     * @return the value of fbs_business_report.department
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.department
     *
     * @param department the value for fbs_business_report.department
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.department_code
     *
     * @return the value of fbs_business_report.department_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.department_code
     *
     * @param departmentCode the value for fbs_business_report.department_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.region
     *
     * @return the value of fbs_business_report.region
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.region
     *
     * @param region the value for fbs_business_report.region
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.region_code
     *
     * @return the value of fbs_business_report.region_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.region_code
     *
     * @param regionCode the value for fbs_business_report.region_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.group_name
     *
     * @return the value of fbs_business_report.group_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.group_name
     *
     * @param groupName the value for fbs_business_report.group_name
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.group_code
     *
     * @return the value of fbs_business_report.group_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.group_code
     *
     * @param groupCode the value for fbs_business_report.group_code
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.deal_shop
     *
     * @return the value of fbs_business_report.deal_shop
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getDealShop() {
        return dealShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.deal_shop
     *
     * @param dealShop the value for fbs_business_report.deal_shop
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setDealShop(String dealShop) {
        this.dealShop = dealShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_business_report.store_number
     *
     * @return the value of fbs_business_report.store_number
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public String getStoreNumber() {
        return storeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_business_report.store_number
     *
     * @param storeNumber the value for fbs_business_report.store_number
     *
     * @mbggenerated Sun Mar 18 13:42:09 CST 2018
     */
    public void setStoreNumber(String storeNumber) {
        this.storeNumber = storeNumber;
    }
}