package com.awelee.model;

public class FbsReceiptReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.id
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.receipt_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String receiptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.business_type
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.contract_no
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.customer_name
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.name_of_owner
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String nameOfOwner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.amount
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.receipt_approver
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String receiptApprover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.receipt_approval_time
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String receiptApprovalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.receipt_item
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String receiptItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.usage_time
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String usageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.recorder
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String recorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.deposit_date
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String depositDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.bank_name
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.bank_card_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String bankCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.serial_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.terminal_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String terminalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.payment_method
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String paymentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.deal_shop
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String dealShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.store_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String storeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.group
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String group;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.group_code
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.region
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fbs_receipt_report.region_code
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    private String regionCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.id
     *
     * @return the value of fbs_receipt_report.id
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.id
     *
     * @param id the value for fbs_receipt_report.id
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.receipt_number
     *
     * @return the value of fbs_receipt_report.receipt_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getReceiptNumber() {
        return receiptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.receipt_number
     *
     * @param receiptNumber the value for fbs_receipt_report.receipt_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.business_type
     *
     * @return the value of fbs_receipt_report.business_type
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.business_type
     *
     * @param businessType the value for fbs_receipt_report.business_type
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.contract_no
     *
     * @return the value of fbs_receipt_report.contract_no
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.contract_no
     *
     * @param contractNo the value for fbs_receipt_report.contract_no
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.customer_name
     *
     * @return the value of fbs_receipt_report.customer_name
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.customer_name
     *
     * @param customerName the value for fbs_receipt_report.customer_name
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.name_of_owner
     *
     * @return the value of fbs_receipt_report.name_of_owner
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getNameOfOwner() {
        return nameOfOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.name_of_owner
     *
     * @param nameOfOwner the value for fbs_receipt_report.name_of_owner
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setNameOfOwner(String nameOfOwner) {
        this.nameOfOwner = nameOfOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.amount
     *
     * @return the value of fbs_receipt_report.amount
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.amount
     *
     * @param amount the value for fbs_receipt_report.amount
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.receipt_approver
     *
     * @return the value of fbs_receipt_report.receipt_approver
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getReceiptApprover() {
        return receiptApprover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.receipt_approver
     *
     * @param receiptApprover the value for fbs_receipt_report.receipt_approver
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setReceiptApprover(String receiptApprover) {
        this.receiptApprover = receiptApprover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.receipt_approval_time
     *
     * @return the value of fbs_receipt_report.receipt_approval_time
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getReceiptApprovalTime() {
        return receiptApprovalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.receipt_approval_time
     *
     * @param receiptApprovalTime the value for fbs_receipt_report.receipt_approval_time
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setReceiptApprovalTime(String receiptApprovalTime) {
        this.receiptApprovalTime = receiptApprovalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.receipt_item
     *
     * @return the value of fbs_receipt_report.receipt_item
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getReceiptItem() {
        return receiptItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.receipt_item
     *
     * @param receiptItem the value for fbs_receipt_report.receipt_item
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setReceiptItem(String receiptItem) {
        this.receiptItem = receiptItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.usage_time
     *
     * @return the value of fbs_receipt_report.usage_time
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getUsageTime() {
        return usageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.usage_time
     *
     * @param usageTime the value for fbs_receipt_report.usage_time
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setUsageTime(String usageTime) {
        this.usageTime = usageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.recorder
     *
     * @return the value of fbs_receipt_report.recorder
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getRecorder() {
        return recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.recorder
     *
     * @param recorder the value for fbs_receipt_report.recorder
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setRecorder(String recorder) {
        this.recorder = recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.deposit_date
     *
     * @return the value of fbs_receipt_report.deposit_date
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getDepositDate() {
        return depositDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.deposit_date
     *
     * @param depositDate the value for fbs_receipt_report.deposit_date
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setDepositDate(String depositDate) {
        this.depositDate = depositDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.bank_name
     *
     * @return the value of fbs_receipt_report.bank_name
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.bank_name
     *
     * @param bankName the value for fbs_receipt_report.bank_name
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.bank_card_number
     *
     * @return the value of fbs_receipt_report.bank_card_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getBankCardNumber() {
        return bankCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.bank_card_number
     *
     * @param bankCardNumber the value for fbs_receipt_report.bank_card_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setBankCardNumber(String bankCardNumber) {
        this.bankCardNumber = bankCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.serial_number
     *
     * @return the value of fbs_receipt_report.serial_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.serial_number
     *
     * @param serialNumber the value for fbs_receipt_report.serial_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.terminal_number
     *
     * @return the value of fbs_receipt_report.terminal_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getTerminalNumber() {
        return terminalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.terminal_number
     *
     * @param terminalNumber the value for fbs_receipt_report.terminal_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setTerminalNumber(String terminalNumber) {
        this.terminalNumber = terminalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.payment_method
     *
     * @return the value of fbs_receipt_report.payment_method
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.payment_method
     *
     * @param paymentMethod the value for fbs_receipt_report.payment_method
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.deal_shop
     *
     * @return the value of fbs_receipt_report.deal_shop
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getDealShop() {
        return dealShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.deal_shop
     *
     * @param dealShop the value for fbs_receipt_report.deal_shop
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setDealShop(String dealShop) {
        this.dealShop = dealShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.store_number
     *
     * @return the value of fbs_receipt_report.store_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getStoreNumber() {
        return storeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.store_number
     *
     * @param storeNumber the value for fbs_receipt_report.store_number
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setStoreNumber(String storeNumber) {
        this.storeNumber = storeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.group
     *
     * @return the value of fbs_receipt_report.group
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.group
     *
     * @param group the value for fbs_receipt_report.group
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setGroup(String group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.group_code
     *
     * @return the value of fbs_receipt_report.group_code
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.group_code
     *
     * @param groupCode the value for fbs_receipt_report.group_code
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.region
     *
     * @return the value of fbs_receipt_report.region
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.region
     *
     * @param region the value for fbs_receipt_report.region
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fbs_receipt_report.region_code
     *
     * @return the value of fbs_receipt_report.region_code
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fbs_receipt_report.region_code
     *
     * @param regionCode the value for fbs_receipt_report.region_code
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }
}