package com.awelee.model;

import java.util.ArrayList;
import java.util.List;

public class FbsReceiptReportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public FbsReceiptReportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberIsNull() {
            addCriterion("receipt_number is null");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberIsNotNull() {
            addCriterion("receipt_number is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberEqualTo(String value) {
            addCriterion("receipt_number =", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberNotEqualTo(String value) {
            addCriterion("receipt_number <>", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberGreaterThan(String value) {
            addCriterion("receipt_number >", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberGreaterThanOrEqualTo(String value) {
            addCriterion("receipt_number >=", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberLessThan(String value) {
            addCriterion("receipt_number <", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberLessThanOrEqualTo(String value) {
            addCriterion("receipt_number <=", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberLike(String value) {
            addCriterion("receipt_number like", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberNotLike(String value) {
            addCriterion("receipt_number not like", value, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberIn(List<String> values) {
            addCriterion("receipt_number in", values, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberNotIn(List<String> values) {
            addCriterion("receipt_number not in", values, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberBetween(String value1, String value2) {
            addCriterion("receipt_number between", value1, value2, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andReceiptNumberNotBetween(String value1, String value2) {
            addCriterion("receipt_number not between", value1, value2, "receiptNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("business_type is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("business_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("business_type =", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("business_type <>", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("business_type >", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("business_type >=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("business_type <", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("business_type <=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("business_type like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("business_type not like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIn(List<String> values) {
            addCriterion("business_type in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotIn(List<String> values) {
            addCriterion("business_type not in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("business_type between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("business_type not between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNull() {
            addCriterion("contract_no is null");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNotNull() {
            addCriterion("contract_no is not null");
            return (Criteria) this;
        }

        public Criteria andContractNoEqualTo(String value) {
            addCriterion("contract_no =", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotEqualTo(String value) {
            addCriterion("contract_no <>", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThan(String value) {
            addCriterion("contract_no >", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThanOrEqualTo(String value) {
            addCriterion("contract_no >=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThan(String value) {
            addCriterion("contract_no <", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThanOrEqualTo(String value) {
            addCriterion("contract_no <=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLike(String value) {
            addCriterion("contract_no like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotLike(String value) {
            addCriterion("contract_no not like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoIn(List<String> values) {
            addCriterion("contract_no in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotIn(List<String> values) {
            addCriterion("contract_no not in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoBetween(String value1, String value2) {
            addCriterion("contract_no between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotBetween(String value1, String value2) {
            addCriterion("contract_no not between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("customer_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("customer_name =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("customer_name <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("customer_name >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_name >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("customer_name <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("customer_name <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("customer_name like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("customer_name not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("customer_name in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("customer_name not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("customer_name between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("customer_name not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerIsNull() {
            addCriterion("name_of_owner is null");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerIsNotNull() {
            addCriterion("name_of_owner is not null");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerEqualTo(String value) {
            addCriterion("name_of_owner =", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerNotEqualTo(String value) {
            addCriterion("name_of_owner <>", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerGreaterThan(String value) {
            addCriterion("name_of_owner >", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("name_of_owner >=", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerLessThan(String value) {
            addCriterion("name_of_owner <", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerLessThanOrEqualTo(String value) {
            addCriterion("name_of_owner <=", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerLike(String value) {
            addCriterion("name_of_owner like", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerNotLike(String value) {
            addCriterion("name_of_owner not like", value, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerIn(List<String> values) {
            addCriterion("name_of_owner in", values, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerNotIn(List<String> values) {
            addCriterion("name_of_owner not in", values, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerBetween(String value1, String value2) {
            addCriterion("name_of_owner between", value1, value2, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andNameOfOwnerNotBetween(String value1, String value2) {
            addCriterion("name_of_owner not between", value1, value2, "nameOfOwner");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(String value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(String value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(String value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(String value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(String value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(String value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLike(String value) {
            addCriterion("amount like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotLike(String value) {
            addCriterion("amount not like", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<String> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<String> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(String value1, String value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(String value1, String value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverIsNull() {
            addCriterion("receipt_approver is null");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverIsNotNull() {
            addCriterion("receipt_approver is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverEqualTo(String value) {
            addCriterion("receipt_approver =", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverNotEqualTo(String value) {
            addCriterion("receipt_approver <>", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverGreaterThan(String value) {
            addCriterion("receipt_approver >", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverGreaterThanOrEqualTo(String value) {
            addCriterion("receipt_approver >=", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverLessThan(String value) {
            addCriterion("receipt_approver <", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverLessThanOrEqualTo(String value) {
            addCriterion("receipt_approver <=", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverLike(String value) {
            addCriterion("receipt_approver like", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverNotLike(String value) {
            addCriterion("receipt_approver not like", value, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverIn(List<String> values) {
            addCriterion("receipt_approver in", values, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverNotIn(List<String> values) {
            addCriterion("receipt_approver not in", values, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverBetween(String value1, String value2) {
            addCriterion("receipt_approver between", value1, value2, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApproverNotBetween(String value1, String value2) {
            addCriterion("receipt_approver not between", value1, value2, "receiptApprover");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeIsNull() {
            addCriterion("receipt_approval_time is null");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeIsNotNull() {
            addCriterion("receipt_approval_time is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeEqualTo(String value) {
            addCriterion("receipt_approval_time =", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeNotEqualTo(String value) {
            addCriterion("receipt_approval_time <>", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeGreaterThan(String value) {
            addCriterion("receipt_approval_time >", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeGreaterThanOrEqualTo(String value) {
            addCriterion("receipt_approval_time >=", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeLessThan(String value) {
            addCriterion("receipt_approval_time <", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeLessThanOrEqualTo(String value) {
            addCriterion("receipt_approval_time <=", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeLike(String value) {
            addCriterion("receipt_approval_time like", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeNotLike(String value) {
            addCriterion("receipt_approval_time not like", value, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeIn(List<String> values) {
            addCriterion("receipt_approval_time in", values, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeNotIn(List<String> values) {
            addCriterion("receipt_approval_time not in", values, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeBetween(String value1, String value2) {
            addCriterion("receipt_approval_time between", value1, value2, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptApprovalTimeNotBetween(String value1, String value2) {
            addCriterion("receipt_approval_time not between", value1, value2, "receiptApprovalTime");
            return (Criteria) this;
        }

        public Criteria andReceiptItemIsNull() {
            addCriterion("receipt_item is null");
            return (Criteria) this;
        }

        public Criteria andReceiptItemIsNotNull() {
            addCriterion("receipt_item is not null");
            return (Criteria) this;
        }

        public Criteria andReceiptItemEqualTo(String value) {
            addCriterion("receipt_item =", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemNotEqualTo(String value) {
            addCriterion("receipt_item <>", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemGreaterThan(String value) {
            addCriterion("receipt_item >", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemGreaterThanOrEqualTo(String value) {
            addCriterion("receipt_item >=", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemLessThan(String value) {
            addCriterion("receipt_item <", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemLessThanOrEqualTo(String value) {
            addCriterion("receipt_item <=", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemLike(String value) {
            addCriterion("receipt_item like", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemNotLike(String value) {
            addCriterion("receipt_item not like", value, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemIn(List<String> values) {
            addCriterion("receipt_item in", values, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemNotIn(List<String> values) {
            addCriterion("receipt_item not in", values, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemBetween(String value1, String value2) {
            addCriterion("receipt_item between", value1, value2, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andReceiptItemNotBetween(String value1, String value2) {
            addCriterion("receipt_item not between", value1, value2, "receiptItem");
            return (Criteria) this;
        }

        public Criteria andUsageTimeIsNull() {
            addCriterion("usage_time is null");
            return (Criteria) this;
        }

        public Criteria andUsageTimeIsNotNull() {
            addCriterion("usage_time is not null");
            return (Criteria) this;
        }

        public Criteria andUsageTimeEqualTo(String value) {
            addCriterion("usage_time =", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeNotEqualTo(String value) {
            addCriterion("usage_time <>", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeGreaterThan(String value) {
            addCriterion("usage_time >", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeGreaterThanOrEqualTo(String value) {
            addCriterion("usage_time >=", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeLessThan(String value) {
            addCriterion("usage_time <", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeLessThanOrEqualTo(String value) {
            addCriterion("usage_time <=", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeLike(String value) {
            addCriterion("usage_time like", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeNotLike(String value) {
            addCriterion("usage_time not like", value, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeIn(List<String> values) {
            addCriterion("usage_time in", values, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeNotIn(List<String> values) {
            addCriterion("usage_time not in", values, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeBetween(String value1, String value2) {
            addCriterion("usage_time between", value1, value2, "usageTime");
            return (Criteria) this;
        }

        public Criteria andUsageTimeNotBetween(String value1, String value2) {
            addCriterion("usage_time not between", value1, value2, "usageTime");
            return (Criteria) this;
        }

        public Criteria andRecorderIsNull() {
            addCriterion("recorder is null");
            return (Criteria) this;
        }

        public Criteria andRecorderIsNotNull() {
            addCriterion("recorder is not null");
            return (Criteria) this;
        }

        public Criteria andRecorderEqualTo(String value) {
            addCriterion("recorder =", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotEqualTo(String value) {
            addCriterion("recorder <>", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderGreaterThan(String value) {
            addCriterion("recorder >", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderGreaterThanOrEqualTo(String value) {
            addCriterion("recorder >=", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLessThan(String value) {
            addCriterion("recorder <", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLessThanOrEqualTo(String value) {
            addCriterion("recorder <=", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLike(String value) {
            addCriterion("recorder like", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotLike(String value) {
            addCriterion("recorder not like", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderIn(List<String> values) {
            addCriterion("recorder in", values, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotIn(List<String> values) {
            addCriterion("recorder not in", values, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderBetween(String value1, String value2) {
            addCriterion("recorder between", value1, value2, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotBetween(String value1, String value2) {
            addCriterion("recorder not between", value1, value2, "recorder");
            return (Criteria) this;
        }

        public Criteria andDepositDateIsNull() {
            addCriterion("deposit_date is null");
            return (Criteria) this;
        }

        public Criteria andDepositDateIsNotNull() {
            addCriterion("deposit_date is not null");
            return (Criteria) this;
        }

        public Criteria andDepositDateEqualTo(String value) {
            addCriterion("deposit_date =", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateNotEqualTo(String value) {
            addCriterion("deposit_date <>", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateGreaterThan(String value) {
            addCriterion("deposit_date >", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateGreaterThanOrEqualTo(String value) {
            addCriterion("deposit_date >=", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateLessThan(String value) {
            addCriterion("deposit_date <", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateLessThanOrEqualTo(String value) {
            addCriterion("deposit_date <=", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateLike(String value) {
            addCriterion("deposit_date like", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateNotLike(String value) {
            addCriterion("deposit_date not like", value, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateIn(List<String> values) {
            addCriterion("deposit_date in", values, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateNotIn(List<String> values) {
            addCriterion("deposit_date not in", values, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateBetween(String value1, String value2) {
            addCriterion("deposit_date between", value1, value2, "depositDate");
            return (Criteria) this;
        }

        public Criteria andDepositDateNotBetween(String value1, String value2) {
            addCriterion("deposit_date not between", value1, value2, "depositDate");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("bank_name is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("bank_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("bank_name =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("bank_name <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("bank_name >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_name >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("bank_name <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("bank_name <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("bank_name like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("bank_name not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("bank_name in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("bank_name not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("bank_name between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("bank_name not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberIsNull() {
            addCriterion("bank_card_number is null");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberIsNotNull() {
            addCriterion("bank_card_number is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberEqualTo(String value) {
            addCriterion("bank_card_number =", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberNotEqualTo(String value) {
            addCriterion("bank_card_number <>", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberGreaterThan(String value) {
            addCriterion("bank_card_number >", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_number >=", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberLessThan(String value) {
            addCriterion("bank_card_number <", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberLessThanOrEqualTo(String value) {
            addCriterion("bank_card_number <=", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberLike(String value) {
            addCriterion("bank_card_number like", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberNotLike(String value) {
            addCriterion("bank_card_number not like", value, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberIn(List<String> values) {
            addCriterion("bank_card_number in", values, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberNotIn(List<String> values) {
            addCriterion("bank_card_number not in", values, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberBetween(String value1, String value2) {
            addCriterion("bank_card_number between", value1, value2, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andBankCardNumberNotBetween(String value1, String value2) {
            addCriterion("bank_card_number not between", value1, value2, "bankCardNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNull() {
            addCriterion("serial_number is null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIsNotNull() {
            addCriterion("serial_number is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNumberEqualTo(String value) {
            addCriterion("serial_number =", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotEqualTo(String value) {
            addCriterion("serial_number <>", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThan(String value) {
            addCriterion("serial_number >", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberGreaterThanOrEqualTo(String value) {
            addCriterion("serial_number >=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThan(String value) {
            addCriterion("serial_number <", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLessThanOrEqualTo(String value) {
            addCriterion("serial_number <=", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberLike(String value) {
            addCriterion("serial_number like", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotLike(String value) {
            addCriterion("serial_number not like", value, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberIn(List<String> values) {
            addCriterion("serial_number in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotIn(List<String> values) {
            addCriterion("serial_number not in", values, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberBetween(String value1, String value2) {
            addCriterion("serial_number between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andSerialNumberNotBetween(String value1, String value2) {
            addCriterion("serial_number not between", value1, value2, "serialNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberIsNull() {
            addCriterion("terminal_number is null");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberIsNotNull() {
            addCriterion("terminal_number is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberEqualTo(String value) {
            addCriterion("terminal_number =", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberNotEqualTo(String value) {
            addCriterion("terminal_number <>", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberGreaterThan(String value) {
            addCriterion("terminal_number >", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberGreaterThanOrEqualTo(String value) {
            addCriterion("terminal_number >=", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberLessThan(String value) {
            addCriterion("terminal_number <", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberLessThanOrEqualTo(String value) {
            addCriterion("terminal_number <=", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberLike(String value) {
            addCriterion("terminal_number like", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberNotLike(String value) {
            addCriterion("terminal_number not like", value, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberIn(List<String> values) {
            addCriterion("terminal_number in", values, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberNotIn(List<String> values) {
            addCriterion("terminal_number not in", values, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberBetween(String value1, String value2) {
            addCriterion("terminal_number between", value1, value2, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andTerminalNumberNotBetween(String value1, String value2) {
            addCriterion("terminal_number not between", value1, value2, "terminalNumber");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodIsNull() {
            addCriterion("payment_method is null");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodIsNotNull() {
            addCriterion("payment_method is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodEqualTo(String value) {
            addCriterion("payment_method =", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodNotEqualTo(String value) {
            addCriterion("payment_method <>", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodGreaterThan(String value) {
            addCriterion("payment_method >", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodGreaterThanOrEqualTo(String value) {
            addCriterion("payment_method >=", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodLessThan(String value) {
            addCriterion("payment_method <", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodLessThanOrEqualTo(String value) {
            addCriterion("payment_method <=", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodLike(String value) {
            addCriterion("payment_method like", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodNotLike(String value) {
            addCriterion("payment_method not like", value, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodIn(List<String> values) {
            addCriterion("payment_method in", values, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodNotIn(List<String> values) {
            addCriterion("payment_method not in", values, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodBetween(String value1, String value2) {
            addCriterion("payment_method between", value1, value2, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andPaymentMethodNotBetween(String value1, String value2) {
            addCriterion("payment_method not between", value1, value2, "paymentMethod");
            return (Criteria) this;
        }

        public Criteria andDealShopIsNull() {
            addCriterion("deal_shop is null");
            return (Criteria) this;
        }

        public Criteria andDealShopIsNotNull() {
            addCriterion("deal_shop is not null");
            return (Criteria) this;
        }

        public Criteria andDealShopEqualTo(String value) {
            addCriterion("deal_shop =", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopNotEqualTo(String value) {
            addCriterion("deal_shop <>", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopGreaterThan(String value) {
            addCriterion("deal_shop >", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopGreaterThanOrEqualTo(String value) {
            addCriterion("deal_shop >=", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopLessThan(String value) {
            addCriterion("deal_shop <", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopLessThanOrEqualTo(String value) {
            addCriterion("deal_shop <=", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopLike(String value) {
            addCriterion("deal_shop like", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopNotLike(String value) {
            addCriterion("deal_shop not like", value, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopIn(List<String> values) {
            addCriterion("deal_shop in", values, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopNotIn(List<String> values) {
            addCriterion("deal_shop not in", values, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopBetween(String value1, String value2) {
            addCriterion("deal_shop between", value1, value2, "dealShop");
            return (Criteria) this;
        }

        public Criteria andDealShopNotBetween(String value1, String value2) {
            addCriterion("deal_shop not between", value1, value2, "dealShop");
            return (Criteria) this;
        }

        public Criteria andStoreNumberIsNull() {
            addCriterion("store_number is null");
            return (Criteria) this;
        }

        public Criteria andStoreNumberIsNotNull() {
            addCriterion("store_number is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNumberEqualTo(String value) {
            addCriterion("store_number =", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberNotEqualTo(String value) {
            addCriterion("store_number <>", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberGreaterThan(String value) {
            addCriterion("store_number >", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberGreaterThanOrEqualTo(String value) {
            addCriterion("store_number >=", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberLessThan(String value) {
            addCriterion("store_number <", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberLessThanOrEqualTo(String value) {
            addCriterion("store_number <=", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberLike(String value) {
            addCriterion("store_number like", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberNotLike(String value) {
            addCriterion("store_number not like", value, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberIn(List<String> values) {
            addCriterion("store_number in", values, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberNotIn(List<String> values) {
            addCriterion("store_number not in", values, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberBetween(String value1, String value2) {
            addCriterion("store_number between", value1, value2, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andStoreNumberNotBetween(String value1, String value2) {
            addCriterion("store_number not between", value1, value2, "storeNumber");
            return (Criteria) this;
        }

        public Criteria andGroupIsNull() {
            addCriterion("group is null");
            return (Criteria) this;
        }

        public Criteria andGroupIsNotNull() {
            addCriterion("group is not null");
            return (Criteria) this;
        }

        public Criteria andGroupEqualTo(String value) {
            addCriterion("group =", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotEqualTo(String value) {
            addCriterion("group <>", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupGreaterThan(String value) {
            addCriterion("group >", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupGreaterThanOrEqualTo(String value) {
            addCriterion("group >=", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLessThan(String value) {
            addCriterion("group <", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLessThanOrEqualTo(String value) {
            addCriterion("group <=", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLike(String value) {
            addCriterion("group like", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotLike(String value) {
            addCriterion("group not like", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupIn(List<String> values) {
            addCriterion("group in", values, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotIn(List<String> values) {
            addCriterion("group not in", values, "group");
            return (Criteria) this;
        }

        public Criteria andGroupBetween(String value1, String value2) {
            addCriterion("group between", value1, value2, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotBetween(String value1, String value2) {
            addCriterion("group not between", value1, value2, "group");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNull() {
            addCriterion("group_code is null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNotNull() {
            addCriterion("group_code is not null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeEqualTo(String value) {
            addCriterion("group_code =", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotEqualTo(String value) {
            addCriterion("group_code <>", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThan(String value) {
            addCriterion("group_code >", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThanOrEqualTo(String value) {
            addCriterion("group_code >=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThan(String value) {
            addCriterion("group_code <", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThanOrEqualTo(String value) {
            addCriterion("group_code <=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLike(String value) {
            addCriterion("group_code like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotLike(String value) {
            addCriterion("group_code not like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIn(List<String> values) {
            addCriterion("group_code in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotIn(List<String> values) {
            addCriterion("group_code not in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeBetween(String value1, String value2) {
            addCriterion("group_code between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotBetween(String value1, String value2) {
            addCriterion("group_code not between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionCodeIsNull() {
            addCriterion("region_code is null");
            return (Criteria) this;
        }

        public Criteria andRegionCodeIsNotNull() {
            addCriterion("region_code is not null");
            return (Criteria) this;
        }

        public Criteria andRegionCodeEqualTo(String value) {
            addCriterion("region_code =", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeNotEqualTo(String value) {
            addCriterion("region_code <>", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeGreaterThan(String value) {
            addCriterion("region_code >", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("region_code >=", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeLessThan(String value) {
            addCriterion("region_code <", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeLessThanOrEqualTo(String value) {
            addCriterion("region_code <=", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeLike(String value) {
            addCriterion("region_code like", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeNotLike(String value) {
            addCriterion("region_code not like", value, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeIn(List<String> values) {
            addCriterion("region_code in", values, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeNotIn(List<String> values) {
            addCriterion("region_code not in", values, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeBetween(String value1, String value2) {
            addCriterion("region_code between", value1, value2, "regionCode");
            return (Criteria) this;
        }

        public Criteria andRegionCodeNotBetween(String value1, String value2) {
            addCriterion("region_code not between", value1, value2, "regionCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 18 03:08:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fbs_receipt_report
     *
     * @mbggenerated Sun Mar 18 03:08:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}